udpate files

diff --git a/utilities/notify b/utilities/notify
--- a/utilities/notify
+++ b/utilities/notify
@@ -18,7 +18,13 @@ case "$#" in
 	if [[ "$1" == "-no-id" ]]; then
 	    notify-send -u low "$2"
 	else
-	    echo "error: not valid argument" 1>&2
+	    notify-send -r 1 -u low "$1" "$2"
+	fi;;
+    3)
+	if [[ "$1" == "-no-id" ]]; then
+	    notify-send -u low "$2" "$3"
+	else
+	    echo "error: no arguments or too many arguments" 1>&2
 	    exit 1
 	fi;;
     *)
